# Generated by Django 2.0.7 on 2018-11-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
